# 打印版本的信息，没啥大用
version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./build/django/Dockerfile
    ports:
    - "7000:7000"
    restart: always
    volumes:
    - /home/BCRUPro
    command: python3 /home/BCRUPro/manage.py runserver 0.0.0.0:7000