# 打印版本的信息，没啥大用
version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: ./build/django/Dockerfile
    ports:
            - "6666:6666"
    restart: always
    volumes:
    - /home/BCRUPro
    command: python3 /home/BCRUPro/manage.py runserver 0.0.0.0:6666
    container_name: "argiculture"
